# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CityGMLModelGenerator
                                 A QGIS plugin
 CityGMLモデル生成ツール
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-02
        copyright            : (C) 2021 by Orbitalnet.inc
        email                : info@orbitalnet.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CityGMLModelGenerator class from file CityGMLModelGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .citygml_model_generator import CityGMLModelGenerator
    return CityGMLModelGenerator(iface)
